- name: "APT - Add Docker GPG key"
  become: yes  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: "APT - Add Docker repository"
  become: yes  
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    #repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
    filename: docker
  
- name: "APT - install misc packages"
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "aptitude"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
  
- name: "APT - install 'docker-ce'"
  become: yes
  apt:
    name: "docker-ce"
    update_cache: yes

- name: Check current docker-compose version
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Add users to docker group.
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"