- name: Download minikube
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: "/usr/local/bin/minikube"
    mode: 0755

- name: Install kubectl
  become: yes
  yum:
    name:
      - kubernetes-client
    state: latest
  when: ansible_facts['os_family']  == 'RedHat'
