apt_packages:
    - apt-transport-https
    - curl
    - git
    - htop
    - jq
    - nmap
    - traceroute
    - unrar
    - vim
    - zsh
    - mc
    - tmux
    - irssi   

rpm_packages:
    - vim
    - curl
    - nmap
    - zsh
    - mc
    - tmux


username: 'nss'
